import hashlib
str = input("Enter a string : ")
md5value = hashlib.md5(str.encode(encoding="utf-8"))
sha512value = hashlib.sha512(str.encode(encoding="utf-8"))
sha3_256value = hashlib.sha3_256(str.encode(encoding="utf-8"))
sha384value = hashlib.sha384(str.encode(encoding="utf-8"))
print("")
print("md5 value is ", end="")
print(md5value.hexdigest())
print("")
print("sha512 value is ", end="")
print(sha512value.hexdigest())
print("")
print("sha3_256 value is ", end="")
print(sha3_256value.hexdigest())
print("")
print("sha384 value is " ,end="")
print(sha384value.hexdigest())

